rvm:
  - 1.9.3
  - 2.0
  - 2.1
gemfile:
  - gemfiles/rails2.gemfile
  - gemfiles/rails3.gemfile
  - gemfiles/rails3.2.gemfile
matrix:
  exclude:
    - rvm: 2.0
      gemfile: gemfiles/rails2.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails3.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails2.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails3.gemfile
